version: '3.3'
services:

  elasticsearch-1:
    container_name: elasticsearch-1
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['cluster.name=pgov-cluster', 'http.host=0.0.0.0', 'transport.host=0.0.0.0']
    volumes: ['esdata1:/usr/share/elasticsearch/data']
    ports: ['0.0.0.0:9200:9200', '0.0.0.0:9300:9300',]
    networks: ['esnet']

  elasticsearch-2:
    container_name: elasticsearch-2
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['cluster.name=pgov-cluster', 'discovery.zen.ping.unicast.hosts=elasticsearch-1']
    volumes: ['esdata2:/usr/share/elasticsearch/data']
    networks: ['esnet']
    depends_on: ['elasticsearch-1']

  elasticsearch-3:
    container_name: elasticsearch-3
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['cluster.name=pgov-cluster', 'discovery.zen.ping.unicast.hosts=elasticsearch-1']
    volumes: ['esdata3:/usr/share/elasticsearch/data']
    networks: ['esnet']
    depends_on: ['elasticsearch-1']

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${TAG}
    environment: ['ELASTICSEARCH_URL=http://10.0.7.1:9200']
    ports: ['0.0.0.0:80:5601']
    networks: ['esnet']
    depends_on: ['elasticsearch-1']

networks: {esnet: {}}
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
