version: '2'

services:

  elasticsearch:
    build:
      context: ./elasticsearch/
      dockerfile: Dockerfile
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:  # exposed to localhost only
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apm_server:
    image: docker.elastic.co/apm/apm-server:6.2.2
    container_name: apm_server
    volumes:
      - ./apm-server/config/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    ports: ['8200:8200']
    networks:
      - elk
    command: -e -E 'apm-server.host=0.0.0.0:8200'
    depends_on: ['elasticsearch']

networks:

  elk:
    driver: bridge
