keystore.path: "/usr/share/heartbeat/config/heartbeat.keystore"

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://elasticsearch:9200
    - http://kibana:5601
  ssl:
    certificate_authorities: ["/certs/ssl/ca/ca.crt"]
  username: elastic
  password: "${ELASTIC_PASSWORD}"

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from heartbeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/certs/ssl/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  ssl.certificate_authorities: ["/certs/ssl/ca/ca.crt"]

xpack.monitoring.enabled: true
