output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "apm"
  password: "apm-server"
  #protocol: "https"
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
  #ssl.certificate: "/etc/pki/client/cert.pem"
  #ssl.key: "/etc/pki/client/cert.key"

setup.kibana:
  host: "kibana:5601"
  username: "kibanaserver"
  password: "kibanaserver"

#setup.dashboards:  # apm-server setup --dashboards
#  enabled: true
  # more settings?

#apm-server.ssl.key
#apm-server.ssl.certificate
# secret token ?
