keystore.path: "/usr/share/apm-server/config/apm-server.keystore"

apm-server.frontend.enabled: true
apm-server.host: "0.0.0.0:8200"

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from apm-server.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/certs/ssl/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  ssl.certificate_authorities: ["/certs/ssl/ca/ca.crt"]
